load_module /usr/lib/nginx/modules/ngx_http_geoip_module.so;

events {}

http {
    geoip_country /usr/share/GeoIP/GeoIP.dat;
    
    server {
        listen 80;
        server_name _;

        # Блокировка российских IP
        if ($geoip_country_code = "RU") {
            return 403 "No entry: access from Russia is blocked.";
        }

        # Все остальные запросы идут к API
        location / {
            # Важно: имя сервиса в docker-compose.yml для app называется "app", а не "arxiv-api" в bridge-сети. 
            # Изменим адрес на внутреннее DNS имя сервиса
            proxy_pass http://app:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
